name: Docker

on:
  push:
    branches:
      - main

    tags:
      - v*

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        repository: bspaulding/food-diary-frontend
        tag_with_ref: true
