name: Migrate Image
on:
  workflow_dispatch:
    inputs:
      sourceRegistry:
        required: true
      sourceRepo:
        required: true
      sourceTag:
        required: true
      targetRegistry:
        required: true
      targetRepo:
        required: true
      targetTag:
        required: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  migrate-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        id: pull
        run: docker pull ${{ inputs.sourceRegistry }}/${{ inputs.sourceRepo }}:${{ inputs.sourceTag }}

      - name: Retag image
        id: retag
        run: docker tag ${{ inputs.sourceRepo }}:${{ inputs.sourceTag }} ${{ inputs.targetRepo }}:${{ inputs.targetTag }}
      - name: Push image
        id: push
        run: docker push ${{ inputs.targetRegistry }}/${{ inputs.targetRepo }}:${{ inputs.targetTag }}

