name: Publish (nutrition-fact-labeller)
on:
  push:
    branches:
      - main
    tags:
      - "nutrition-fact-labeller-v*"
jobs:
  publish:
    uses: ./.github/workflows/publish-image.yml
    with:
      component: nutrition-fact-labeller
      context: nutrition-fact-labeller
      file: nutrition-fact-labeller/Containerfile
    secrets: inherit
