name: Publish (llm-nutrition-api)
on:
  push:
    branches:
      - main
    tags:
      - "llm-nutrition-api-v*"
permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write
jobs:
  publish:
    uses: ./.github/workflows/publish-image.yml
    with:
      component: llm-nutrition-api
      context: llm-nutrition-api
      file: llm-nutrition-api/Containerfile
    secrets: inherit
