name: Publish (nutrition-fact-labeller)
on:
  push:
    branches:
      - main
    tags:
      - "nutrition-fact-labeller-v*"
permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write
jobs:
  publish:
    uses: ./.github/workflows/publish-image.yml
    with:
      component: nutrition-fact-labeller
      context: nutrition-fact-labeller
      file: nutrition-fact-labeller/Containerfile
    secrets: inherit
