name: Publish (graphql-engine)
on:
  push:
    branches:
      - main
    tags:
      - "graphql-engine-v*"
jobs:
  publish:
    uses: ./.github/workflows/publish-image.yml
    with:
      component: graphql-engine
      context: graphql-engine
    secrets: inherit
